# Generated by Django 6.0.4 on 2026-04-24 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_currency",
                    models.CharField(
                        choices=[
                            ("GBP", "Pound Sterling"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="GBP",
                        max_length=3,
                    ),
                ),
                (
                    "receiver_currency",
                    models.CharField(
                        choices=[
                            ("GBP", "Pound Sterling"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="GBP",
                        max_length=3,
                    ),
                ),
                ("amount_sent", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount_received",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("transaction_created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequestPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requester_currency",
                    models.CharField(
                        choices=[
                            ("GBP", "Pound Sterling"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "requested_from_currency",
                    models.CharField(
                        choices=[
                            ("GBP", "Pound Sterling"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "amount_to_send",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "amount_to_receive",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=8,
                    ),
                ),
                ("transaction_created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_from",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requester",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("GBP", "Pound Sterling"),
                            ("EUR", "Euro"),
                            ("USD", "US Dollar"),
                        ],
                        default="GBP",
                        max_length=3,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=500, max_digits=10),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
